---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - git:
        repo=https://github.com/isucon/isucon5-qualify.git
        dest=/home/isucon/isucon5-qualify
    - name: ruby
      shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
      args:
        chdir: /home/isucon/isucon5-qualify/bench
    - name: java build
      shell: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 gradle compileJava
      args:
        chdir: /home/isucon/isucon5-qualify/bench

- hosts: all
  gather_facts: no
  tasks:
    - copy: src=../files/env.bench.sh dest=/home/isucon/env.bench.sh owner=isucon mode=644
    - name: ruby (systemd)
      copy: src=../files/systemd.ruby.service dest=/etc/systemd/system/agent.ruby.service owner=root mode=644
    - name: default application selection
      service: name=agent.ruby state=running enabled=true
