---
- hosts: all
  gather_facts: no
  tasks:
    - apt: name=python-selinux state=present update_cache=true
    - service: name=apparmor enabled=no state=stopped
    - apt: name=git state=present
    - apt: name=gcc state=present
    - apt: name=patch state=present
    - apt: name=autoconf state=present
    - apt: name=automake state=present
    - apt: name=bison state=present
    - apt: name=build-essential
    - apt: name=libssl-dev state=present
    - apt: name=libyaml-dev state=present
    - apt: name=libreadline6-dev state=present
    - apt: name=zlib1g-dev state=present
    - apt: name=libncurses5-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=libgdbm3 state=present
    - apt: name=libgdbm-dev state=present
    - apt: name=libmysqlclient-dev state=present
    - apt: name=libcurl4-openssl-dev state=present
    - apt: name=libjpeg-turbo8 state=present
    - apt: name=libjpeg-turbo8-dev state=present
    - apt: name=libpng12-0 state=present
    - apt: name=libpng12-dev state=present
    - apt: name=libmcrypt4 state=present
    - apt: name=libmcrypt-dev state=present
    - apt: name=libtidy-0.99-0 state=present
    - apt: name=libtidy-dev state=present
    - apt: name=libxml2-dev state=present
    - apt: name=libxslt1-dev state=present
    - apt: name=readline-common state=present
    - apt: name=re2c state=present
    # for php --with-openssl
    - apt: name=pkg-config
    # make Ubuntu 15.04 image root fs to rw 
    - copy: src=../files/grub.cfg dest=/boot/grub/grub.cfg owner=root mode=444
