---
- hosts: all
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.2.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v0.12.7 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    # python2
    - command: /home/isucon/.xbuild/python-install 2.7.10 /home/isucon/.local/python
      args:
        creates: /home/isucon/.local/python/bin/python
    # python3
    - command: /home/isucon/.xbuild/python-install 3.4.3 /home/isucon/.local/python3
      args:
        creates: /home/isucon/.local/python3/bin/python
    # perl
    - command: /home/isucon/.xbuild/perl-install 5.20.2 /home/isucon/.local/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl
    # php
    - command: /home/isucon/.xbuild/php-install 5.6.13 /home/isucon/.local/php -- --with-pear --with-openssl
      args:
        creates: /home/isucon/.local/php/bin/php
    - copy: src=../files/php.ini dest=/home/isucon/.local/php/etc/php.ini owner=isucon mode=644
    # golang
    - command: /home/isucon/.xbuild/go-install 1.5 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go
    # scala
    - shell: curl http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz | (cd /home/isucon/.local && tar xzf -)
      args:
        creates: /home/isucon/.local/scala-2.11.7/bin/scala
    - file: src=/home/isucon/.local/scala-2.11.7 dest=/home/isucon/.local/scala state=link

- hosts: all
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
