---
- hosts: all
  gather_facts: no
  tasks:
    - name: change timezone to JST
      shell: cp -p /usr/share/zoneinfo/Japan /etc/localtime
    - group: name=wheel
    - user: name=isucon groups=wheel
    - copy: src=../files/bashrc dest=/home/isucon/.bashrc owner=isucon mode=755
    - lineinfile: dest=/etc/sudoers state=present regexp='^%wheel ALL\=' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
