---
- hosts: all
  gather_facts: no
  tasks:
    - apt: name=nginx state=present
    - service: name=nginx state=running enabled=true
    - copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=644
      notify:
        - reload nginx
    - copy: src=../files/nginx.php.conf dest=/etc/nginx/nginx.php.conf owner=root mode=644
    - apt: name=mysql-server-5.6 state=present
    - file: path=/var/run/mysqld state=directory owner=mysql mode=775
    - name: copy my.cnf
      copy: src=../files/my.cnf dest=/etc/my.cnf owner=root mode=644
      notify:
        - restart mysqld
    - service: name=mysql state=running enabled=true
    - apt: name=python-mysqldb state=present
    - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
  handlers:
    - name: restart mysqld
      action: service name=mysql state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted
